Debug = true
MqttUrl = "mqtt://mosquitto:1883"
MqttCaCert = ""
MqttClientCert = ""
MqttClientKey = ""
NatsUrl = "nats://nats:4222"
NodemanApiUrl = "https://localhost/api/v1"

[[Bridges]]
Direction = "up"
MqttTopic = "events/up/tmp-key-itest"
NatsSubject = "events.up.some_event"
NatsQueue = "eventQ"
Key = "/etc/dnstapir/mqtt-bridge/testkey.json"
Schema = ""

[[Bridges]]
Direction = "down"
MqttTopic = "observations/down/tapir-pop"
NatsSubject = "observations.down.tapir-pop"
NatsQueue = "observationsQ"
Key = "/etc/dnstapir/mqtt-bridge/testkey.json"
Schema = "/etc/dnstapir/mqtt-bridge/edge_observations.json"
